#!/bin/sh

itDisplaysUsageWhenGettingCallCountWithoutArgs() {
    assertEquals 'usage message was not displayed' 'Usage: getSpyCallCount SPY' "$(getSpyCallCount 2>&1)"
}

itReturns1WhenGettingCallCountWithoutArgs() {
    getSpyCallCount >/dev/null
    assertEquals 1 $?
}

itOutputs0WhenGettingCallCountOfSpyNeverCalled() {
    doOrDie createSpy dosomething
    assertEquals '0' "$(getSpyCallCount dosomething 2>&1)"
}

itOutputs1WhenGettingCallCountOfSpyCalledOnce() {
    doOrDie createSpy dosomething

    dosomething

    assertEquals '1' "$(getSpyCallCount dosomething 2>&1)"
}

itOutputs2WhenGettingCallCountOfSpyCalledTwice() {
    doOrDie createSpy dosomething

    dosomething
    dosomething

    assertEquals '2' "$(getSpyCallCount dosomething 2>&1)"
}

itOutputs1WhenGettingCallCountOfSpyCalledOnceInSubshell() {
    doOrDie createSpy dosomething

    (dosomething)

    assertEquals '1' "$(getSpyCallCount dosomething 2>&1)"
}

itOutputsCorrectCallCountsForMultipleSpies() {
    doOrDie createSpy dosomething
    doOrDie createSpy dosomethingelse

    dosomething

    assertEquals 'call count output for wrong spy' '1' "$(getSpyCallCount dosomething 2>&1)"
    assertEquals 'call count output for wrong spy' '0' "$(getSpyCallCount dosomethingelse 2>&1)"
}
