#!/bin/sh

testCanStubTouchCommand() {
    createSpy touch

    touch nonexistent_file

    assertCalledOnceWith touch nonexistent_file

    [ -f nonexistent_file ]
    assertFalse 'nonexistent_file is not a file' $?
}

# mkdir is trikier because the implementation of shpy calls mkdir
testCanStubMkdirCommand() {
    createSpy -r 123 mkdir

    mkdir -p nonexistent_dir

    assertEquals "\`mkdir\` returns val passed to createSpy" 123 $?

    assertCalledOnceWith mkdir -p nonexistent_dir

    [ -d nonexistent_dir ]
    assertFalse 'nonexistent_dir is not a dir' $?
}
