#!/usr/bin/env sh

itDisplaysUsageWhenExaminingNextCallWithoutArgs() {
    assertEquals 'usage message was not displayed' \
      'Usage: examineNextSpyCall name' \
      "$(examineNextSpyCall 2>&1 | head -n1)"
}

itReturns1WhenExaminingNextCallWithoutArgs() {
    examineNextSpyCall >/dev/null
    assertEquals 1 $?
}

itDisplaysNothingWhenExaminingNextCallOfSpyNeverCalled() {
    doOrDie createSpy dosomething
    assertEquals 'unexpected output' '' "$(examineNextSpyCall dosomething 2>&1)"
}

itReturns0WhenExaminingNextCallOfSpyNeverCalled() {
    doOrDie createSpy dosomething
    examineNextSpyCall dosomething

    assertTrue "returned non-zero exit status" $?
}

itDisplaysNothingWhenExaminingNextCallOfSpyCalledOnce() {
    doOrDie createSpy dosomething
    dosomething

    assertEquals 'unexpected output' '' "$(examineNextSpyCall dosomething 2>&1)"
}

itReturns1WhenExaminingNextCallOfSpyCalledOnce() {
    doOrDie createSpy dosomething
    dosomething

    examineNextSpyCall dosomething

    assertTrue "returned non-zero exit status" $?
}

itDisplaysErrorWhenCheckingIfSpyWasCalledAfterExamingNextCallOnLastCall() {
    doOrDie createSpy dosomething
    dosomething

    examineNextSpyCall dosomething >/dev/null

    printf '%s' "$(wasSpyCalledWith dosomething 2>&1  >/dev/null)" | grep -q '^Error:'
    assertTrue 'output begins with "Error:"' $?
}

itDisplaysErrorWhenCheckingIfSpyWasCalledAfterExamingNextCallOnLastCallInNewShell() {
    doOrDie createSpy dosomething
    runInNewShell dosomething

    examineNextSpyCall dosomething >/dev/null

    printf '%s' "$(wasSpyCalledWith dosomething 2>&1  >/dev/null)" | grep -q '^Error:'
    assertTrue 'output begins with "Error:" from new shell' $?
}

itReturns1WhenCheckingIfSpyWasCalledAfterExamingNextCallOnLastCall() {
    doOrDie createSpy dosomething
    dosomething

    examineNextSpyCall dosomething
    wasSpyCalledWith dosomething >/dev/null 2>&1

    assertEquals 1 $?
}

itReturns1WhenCheckingIfSpyWasCalledAfterExamingNextCallOnLastCallInNewShell() {
    doOrDie createSpy dosomething
    runInNewShell dosomething

    examineNextSpyCall dosomething
    wasSpyCalledWith dosomething >/dev/null 2>&1

    assertEquals 1 $?
}

itChecksTheNextCallWhenExamingNextSpyCall() {
    doOrDie createSpy dosomething

    dosomething
    dosomething somearg

    wasSpyCalledWith dosomething
    assertTrue 'checking first spy call with no args gave wrong result' $?

    examineNextSpyCall dosomething
    wasSpyCalledWith dosomething somearg

    assertTrue 'checking second spy call with args gave wrong result' $?
}

itChecksTheNextCallWhenExamingNextSpyCallInNewShell() {
    doOrDie createSpy dosomething

    runInNewShell dosomething
    runInNewShell dosomething somearg

    wasSpyCalledWith dosomething
    assertTrue 'checking first spy call with no args gave wrong result in new shell' $?

    examineNextSpyCall dosomething
    wasSpyCalledWith dosomething somearg

    assertTrue 'checking second spy call with args gave wrong result in new shell' $?
}
