#!/usr/bin/env sh

itRunsTestsWithNounset() {
  # if nounset is set, this subshell will exit with a nonzero status
  # `|| false` is needed for kcov v33 to mark this line as hit
  # shellcheck disable=SC2154
  (printf '%s\n' "$nonexistent_variable") 2>/dev/null || false

  assertFalse 'nounset is not set in the test environment' $?
}

itReturns1WhenShpyPathVariableIsNotSet() {
    # shellcheck disable=SC2039
    local original_shpy_path
    original_shpy_path="$SHPY_PATH"
    unset SHPY_PATH

    # shellcheck source=/dev/null
    . "$original_shpy_path" >/dev/null 2>&1
    assertEquals 1 $?

    SHPY_PATH="$original_shpy_path"
    export SHPY_PATH
}

itDisplaysErrorMessageWhenShpyPathVariableIsNotSet() {
    # shellcheck disable=SC2039
    local original_shpy_path
    original_shpy_path="$SHPY_PATH"
    unset SHPY_PATH

    # shellcheck source=/dev/null
    assertEquals 'Error: SHPY_PATH is not set as the path to shpy' "$(. "$original_shpy_path" 2>&1 >/dev/null)"

    SHPY_PATH="$original_shpy_path"
    export SHPY_PATH
}
