#!/bin/sh

itDisplaysUsageWhenExaminingNextCallWithoutArgs() {
    assertEquals 'usage message was not displayed' 'Usage: examineNextSpyCall SPY' "$(examineNextSpyCall 2>&1)"
}

itReturns1WhenExaminingNextCallWithoutArgs() {
    examineNextSpyCall >/dev/null
    assertEquals 1 $?
}

itDisplaysNothingWhenExaminingNextCallOfSpyNeverCalled() {
    doOrDie createSpy dosomething
    assertEquals 'unexpected output' '' "$(examineNextSpyCall dosomething 2>&1)"
}

itReturns0WhenExaminingNextCallOfSpyNeverCalled() {
    doOrDie createSpy dosomething
    examineNextSpyCall dosomething

    assertTrue "returned non-zero exit status" $?
}

itDisplaysNothingWhenExaminingNextCallOfSpyCalledOnce() {
    doOrDie createSpy dosomething
    dosomething

    assertEquals 'unexpected output' '' "$(examineNextSpyCall dosomething 2>&1)"
}

itReturns1WhenExaminingNextCallOfSpyCalledOnce() {
    doOrDie createSpy dosomething
    dosomething

    examineNextSpyCall dosomething

    assertTrue "returned non-zero exit status" $?
}

itDisplaysErrorWhenCheckingIfSpyWasCalledAfterExamingNextCallOnLastCall() {
    doOrDie createSpy dosomething
    dosomething

    examineNextSpyCall dosomething >/dev/null

    printf '%s' "$(wasSpyCalledWith dosomething 2>&1  >/dev/null)" | grep -q '^Error:'
    assertTrue 'output begins with "Error:"' $?
}

itReturns1WhenCheckingIfSpyWasCalledAfterExamingNextCallOnLastCall() {
    doOrDie createSpy dosomething
    dosomething

    examineNextSpyCall dosomething
    wasSpyCalledWith dosomething >/dev/null 2>&1

    assertEquals 1 $?
}

itChecksTheNextCallWhenExamingNextSpyCall() {
    doOrDie createSpy dosomething

    dosomething
    dosomething somearg

    wasSpyCalledWith dosomething
    assertTrue "checking first spy call with no args gave wrong result" $?

    examineNextSpyCall dosomething
    wasSpyCalledWith dosomething somearg

    assertTrue "checking second spy call with args gave wrong result" $?
}
