#!/bin/sh

itDisplaysUsageWhenWasSpyCalledWithHasTooFewArgs() {
    assertEquals 'usage message was not displayed' 'Usage: wasSpyCalledWith SPY [ARG]...' "$(wasSpyCalledWith 2>&1)"
}

itReturns1WhenWasSpyCalledWithHasTooFewArgs() {
    wasSpyCalledWith >/dev/null
    assertEquals 1 $?
}

itDisplaysErrorWhenWasSpyCalledWithHasInvalidSpy() {
    printf '%s\n' "$(wasSpyCalledWith invalidSpy 2>&1 >/dev/null)" | grep -q '^Error:'
    assertTrue 'output does not begin with "Error:"' $?
}

itReturns1WhenWasSpyCalledWithHasInvalidSpy() {
    wasSpyCalledWith invalidSpy >/dev/null 2>&1
    assertEquals 1 $?
}

itDisplaysNothingWhenWasSpyCalledWithPassesWithNoSpyArgs() {
    doOrDie createSpy dosomething
    dosomething

    assertEquals 'unexpected output' '' "$(wasSpyCalledWith dosomething 2>&1)"
}

itDisplaysNothingWhenWasSpyCalledWithPassesWithNoSpyArgsInNewShell() {
    doOrDie createSpy dosomething
    runInNewShell dosomething

    assertEquals 'unexpected output from new shell' '' "$(wasSpyCalledWith dosomething 2>&1)"
}

itReturns0WhenWasSpyCalledWithPassesWithNoSpyArgs() {
    doOrDie createSpy dosomething
    dosomething

    wasSpyCalledWith dosomething
    assertEquals 0 $?
}

itReturns0WhenWasSpyCalledWithPassesWithNoSpyArgsInNewShell() {
    doOrDie createSpy dosomething
    runInNewShell dosomething

    wasSpyCalledWith dosomething
    assertEquals 0 $?
}

itDisplaysNothingWhenWasSpyCalledWithPassesWithOneSpyArg() {
    doOrDie createSpy dosomething
    dosomething 123

    assertEquals 'unexpected output' '' "$(wasSpyCalledWith dosomething 123 2>&1)"
}

itDisplaysNothingWhenWasSpyCalledWithPassesWithOneSpyArgInNewShell() {
    doOrDie createSpy dosomething
    runInNewShell dosomething 123

    assertEquals 'unexpected output from new shell' '' "$(wasSpyCalledWith dosomething 123 2>&1)"
}

itReturns0WhenWasSpyCalledWithPassesWithOneSpyArg() {
    doOrDie createSpy dosomething
    dosomething 123

    wasSpyCalledWith dosomething 123
    assertEquals 0 $?
}

itReturns0WhenWasSpyCalledWithPassesWithOneSpyArgInNewShell() {
    doOrDie createSpy dosomething
    runInNewShell dosomething 123

    wasSpyCalledWith dosomething 123
    assertEquals 0 $?
}

itDisplaysNothingWhenWasSpyCalledWithPassesWithTwoSpyArgs() {
    doOrDie createSpy dosomething
    dosomething 123 456

    assertEquals 'unexpected output' '' "$(wasSpyCalledWith dosomething 123 456 2>&1)"
}

itDisplaysNothingWhenWasSpyCalledWithPassesWithTwoSpyArgsInNewShell() {
    doOrDie createSpy dosomething
    runInNewShell dosomething 123 456

    assertEquals 'unexpected output from new shell' '' "$(wasSpyCalledWith dosomething 123 456 2>&1)"
}

itReturns0WhenWasSpyCalledWithPassesWithTwoSpyArgs() {
    doOrDie createSpy dosomething
    dosomething 123 456

    wasSpyCalledWith dosomething 123 456
    assertEquals 0 $?
}

itReturns0WhenWasSpyCalledWithPassesWithTwoSpyArgsInNewShell() {
    doOrDie createSpy dosomething
    runInNewShell dosomething 123 456

    wasSpyCalledWith dosomething 123 456
    assertEquals 0 $?
}

itDisplaysNothingWhenWasSpyCalledWithFailsWithNonexistentSpyArgs() {
    doOrDie createSpy dosomething
    dosomething

    assertEquals 'unexpected output' '' "$(wasSpyCalledWith dosomething 123 2>&1)"
}

itDisplaysNothingWhenWasSpyCalledWithFailsWithNonexistentSpyArgsInNewShell() {
    doOrDie createSpy dosomething
    runInNewShell dosomething

    assertEquals 'unexpected output from new shell' '' "$(wasSpyCalledWith dosomething 123 2>&1)"
}

itReturns1WhenWasSpyCalledWithPassesWithNonexistentSpyArgs() {
    doOrDie createSpy dosomething
    dosomething

    wasSpyCalledWith dosomething 123
    assertEquals 1 $?
}

itReturns1WhenWasSpyCalledWithPassesWithNonexistentSpyArgsInNewShell() {
    doOrDie createSpy dosomething
    runInNewShell dosomething

    wasSpyCalledWith dosomething 123
    assertEquals 1 $?
}

itDisplaysNothingWhenWasSpyCalledWithFailsMatchingEmptyStringToNoArgs() {
    doOrDie createSpy dosomething
    dosomething ''

    assertEquals 'unexpected output' '' "$(wasSpyCalledWith dosomething 2>&1)"
}

itDisplaysNothingWhenWasSpyCalledWithFailsMatchingEmptyStringToNoArgsInNewShell() {
    doOrDie createSpy dosomething
    runInNewShell dosomething '""'

    assertEquals 'unexpected output from new shell' '' "$(wasSpyCalledWith dosomething 2>&1)"
}

itReturns1WhenWasSpyCalledWithFailsMatchingEmptyStringToNoArgs() {
    doOrDie createSpy dosomething
    dosomething ''

    wasSpyCalledWith dosomething
    assertEquals 1 $?
}

itReturns1WhenWasSpyCalledWithFailsMatchingEmptyStringToNoArgsInNewShell() {
    doOrDie createSpy dosomething
    runInNewShell dosomething '""'

    wasSpyCalledWith dosomething
    assertEquals 1 $?
}

itDisplaysNothingWhenWasSpyCalledWithPassesWithWhitespaceInArgs() {
    doOrDie createSpy dosomething
    dosomething "$(printf ' line 1\nline 2\n\tline 3\nline 4  ')"

    assertEquals 'unexpected output' '' "$(wasSpyCalledWith dosomething "$(printf ' line 1\nline 2\n\tline 3\nline 4  ')" 2>&1)"
}

itDisplaysNothingWhenWasSpyCalledWithPassesWithWhitespaceInArgsInNewShell() {
    doOrDie createSpy dosomething
    runInNewShell "dosomething '$(printf ' line 1\nline 2\n\tline 3\nline 4  ')'"

    assertEquals 'unexpected output from new shell' '' "$(wasSpyCalledWith dosomething "$(printf ' line 1\nline 2\n\tline 3\nline 4  ')" 2>&1)"
}

itReturns0WhenWasSpyCalledWithPassesWithWhitespaceInArgs() {
    doOrDie createSpy dosomething
    dosomething "$(printf ' line 1\nline 2\n\tline 3\nline 4  ')"

    wasSpyCalledWith dosomething "$(printf ' line 1\nline 2\n\tline 3\nline 4  ')"
    assertEquals 0 $?
}

itReturns0WhenWasSpyCalledWithPassesWithWhitespaceInArgsInNewShell() {
    doOrDie createSpy dosomething
    runInNewShell "dosomething '$(printf ' line 1\nline 2\n\tline 3\nline 4  ')'"

    wasSpyCalledWith dosomething "$(printf ' line 1\nline 2\n\tline 3\nline 4  ')"
    assertEquals 0 $?
}
