version: '3.4'

services:
  base:
    build:
      context: .
      target: shpy
    image: shpy:local
  ash:
    image: shpy:local
    depends_on: [base]
    command: sh ${CMD:-/shpy/test/run_tests}
    volumes:
      - ./:/shpy:ro
  bash:
    image: shpy:local
    depends_on: [base]
    command: bash ${CMD:-/shpy/test/run_tests}
    volumes:
      - ./:/shpy:ro
  checkbashisms:
    image: shpy:local
    depends_on: [base]
    working_dir: /shpy
    command: sh -c 'checkbashisms shpy* test/* examples/*/test.sh examples/renamer/renamer /shpy/examples/coverfetch/coverfetch'
    volumes:
      - ./:/shpy:ro
  dash:
    image: shpy:local
    depends_on: [base]
    command: dash ${CMD:-/shpy/test/run_tests}
    volumes:
      - ./:/shpy:ro
  kcov:
    build:
      context: .
      target: kcov
    command: kcov --exclude-path=/usr/local/bin --exclude-pattern=.yml /coverage ${CMD:-/shpy/test/run_tests}
    volumes:
      - ./coverage:/coverage
      - ./:/shpy:ro
  mksh:
    image: shpy:local
    depends_on: [base]
    command: mksh ${CMD:-/shpy/test/run_tests}
    volumes:
      - ./:/shpy:ro
  shellcheck:
    image: shpy:local
    depends_on: [base]
    working_dir: /shpy
    command: sh -c 'shellcheck -x shpy* test/* examples/*/test.sh examples/renamer/renamer examples/coverfetch/coverfetch'
    volumes:
      - ./:/shpy:ro
  zsh:
    image: shpy:local
    depends_on: [base]
    environment: ['SHUNIT_PARENT=run_tests']
    command: zsh -o shwordsplit ${CMD:-/shpy/test/run_tests}
    volumes:
      - ./:/shpy:ro
