#!/bin/sh

testTestEnvironmentHasSet_nounset() {
  # if nounset is set, this subshell will exit with a nonzero status
  # shellcheck disable=SC2154
  (printf '%s\n' "$nonexistent_variable") 2>/dev/null

  assertFalse 'nounset is not set in the test environment' $?
}
