#!/bin/sh

readonly TEST_DIR="$(dirname "$0")"

# shellcheck source=/dev/null
. "$TEST_DIR/../shpy"

createSpy() {
    createSpyArg="$1"
}

testCreateStub_IsAliasForCreateSpy() {
    # shellcheck disable=SC2039
    local createSpyArg

    createStub someStub

    assertEquals someStub "$createSpyArg"
}

# shellcheck source=/dev/null
. "$TEST_DIR/shunit2"
