#!/bin/sh

readonly TEST_DIR="$(dirname "$0")"

# shellcheck source=/dev/null
. "$TEST_DIR/../shpy"

testTestEnvironmentHasSet_nounset() {
  # if nounset is set, this subshell will exit with a nonzero status
  # shellcheck disable=SC2154
  (printf '%s\n' "$nonexistent_variable") 2>/dev/null

  assertFalse 'nounset is not set in the test environment' $?
}

# shellcheck source=/dev/null
. "$TEST_DIR/shunit2"
