#!/bin/sh

readonly TEST_DIR="$(dirname "$0")"

# shellcheck source=/dev/null
. "$TEST_DIR/../shpy"

testWithNoArguments_ShouldReturnUsage() {
    # shellcheck disable=SC2039
    local output
    output=$(createSpy)

    assertFalse 'returns error' $?
    printf '%s\n' "$output" | grep -q '^Usage:'
    assertTrue 'begins with "Usage:"' $?
}

testWithNoArguments_ShouldDieWithUnsupportedFlags() {
    # shellcheck disable=SC2039
    local output
    output=$(createSpy -z 2>&1)

    assertFalse 'returns error' $?
    assertEquals 'Error: Unknown option -z' "$output"
}

testWithNoArguments_ShouldDieWhenRequiredArgumentIsMissing() {
    # shellcheck disable=SC2039
    local output
    output=$(createSpy -r dosomething 2>&1)

    assertFalse 'returns error' $?
    assertEquals 'Error: Missing spy name' "$output"
}

testWithOneArgument_ShouldCreateFunction() {
    createSpy dosomething || fail 'createSpy dosomething'

    command -V dosomething | grep -q function
    assertTrue 'dosomething is a function' $?
}

testShouldStubReturnValue() {
    createSpy -r 123 dosomething || fail 'createSpy dosomething'

    dosomething

    assertEquals 'return value equals passed val' 123 $?
}

testShouldStubReturnValue_PerSpy() {
    createSpy -r 123 dosomething || fail 'createSpy -r 123 dosomething'
    createSpy -r 234 domore || fail 'createSpy -r 234 domore'

    dosomething
    assertEquals 'dosomething return value is 123' 123 $?
    domore
    assertEquals 'domore return value is 234' 234 $?
}

testShouldResetStubReturnValue() {
    createSpy -r 123 dosomething || fail 'createSpy -r 123 dosomething'

    createSpy dosomething

    dosomething
    assertTrue 'dosomething returns the default -- success' $?
}

testShouldStubOutput() {
    # shellcheck disable=SC2039
    local output
    # shellcheck disable=SC2039
    local output_arg='some
output'
    createSpy -o "$output_arg" dosomething || fail 'createSpy dosomething'

    output=$(dosomething)

    assertTrue "\`dosomething\` succeeds" $?
    assertEquals 'output is the passed value' 'some
output' "$output"
}

testShouldResetStubOutput() {
    # shellcheck disable=SC2039
    local output
    createSpy -o 'some output' dosomething || fail 'createSpy dosomething'

    output=$(createSpy dosomething)

    assertTrue "\`createSpy dosomething\` succeeds" $?
    assertNull 'output is unset' "$output"
}

testShouldResetCallCount() {
    createSpy dosomething || fail 'createSpy dosomething'
    dosomething

    createSpy dosomething

    assertTrue "\`createSpy dosomething\` succeeds" $?
    assertEquals 0 "$(getSpyCallCount dosomething)"
}

oneTimeTearDown() {
    cleanupSpies
}

# shellcheck source=/dev/null
. "$TEST_DIR/shunit2"
